[2025-03-31T08:37:25.540+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-31T08:37:25.558+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v5.first_task scheduled__2025-03-30T00:00:00+00:00 [queued]>
[2025-03-31T08:37:25.568+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v5.first_task scheduled__2025-03-30T00:00:00+00:00 [queued]>
[2025-03-31T08:37:25.568+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-31T08:37:25.583+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): first_task> on 2025-03-30 00:00:00+00:00
[2025-03-31T08:37:25.589+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2769) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-31T08:37:25.591+0000] {standard_task_runner.py:72} INFO - Started process 2776 to run task
[2025-03-31T08:37:25.589+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'first_task', 'scheduled__2025-03-30T00:00:00+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpi00h58ig']
[2025-03-31T08:37:25.592+0000] {standard_task_runner.py:105} INFO - Job 93: Subtask first_task
[2025-03-31T08:37:25.642+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v5.first_task scheduled__2025-03-30T00:00:00+00:00 [running]> on host 9663692256f6
[2025-03-31T08:37:25.725+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='our_first_dag_v5' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-30T00:00:00+00:00'
[2025-03-31T08:37:25.726+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-31T08:37:25.743+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-31T08:37:25.744+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world, this is the first task!']
[2025-03-31T08:37:25.752+0000] {subprocess.py:99} INFO - Output:
[2025-03-31T08:37:25.754+0000] {subprocess.py:106} INFO - hello world, this is the first task!
[2025-03-31T08:37:25.755+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-31T08:37:25.779+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-31T08:37:25.779+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=first_task, run_id=scheduled__2025-03-30T00:00:00+00:00, execution_date=20250330T000000, start_date=20250331T083725, end_date=20250331T083725
[2025-03-31T08:37:25.817+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-31T08:37:25.842+0000] {taskinstance.py:3901} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-03-31T08:37:25.844+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
