[2025-04-01T00:00:01.527+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-01T00:00:01.546+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v5.second_task scheduled__2025-03-31T00:00:00+00:00 [queued]>
[2025-04-01T00:00:01.555+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v5.second_task scheduled__2025-03-31T00:00:00+00:00 [queued]>
[2025-04-01T00:00:01.555+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-01T00:00:01.566+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): second_task> on 2025-03-31 00:00:00+00:00
[2025-04-01T00:00:01.573+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=17049) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-01T00:00:01.575+0000] {standard_task_runner.py:72} INFO - Started process 17051 to run task
[2025-04-01T00:00:01.573+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'second_task', 'scheduled__2025-03-31T00:00:00+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmphztyp3pe']
[2025-04-01T00:00:01.576+0000] {standard_task_runner.py:105} INFO - Job 109: Subtask second_task
[2025-04-01T00:00:01.619+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v5.second_task scheduled__2025-03-31T00:00:00+00:00 [running]> on host 9663692256f6
[2025-04-01T00:00:01.701+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='our_first_dag_v5' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-31T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-31T00:00:00+00:00'
[2025-04-01T00:00:01.702+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-01T00:00:01.718+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-01T00:00:01.719+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, I am task2 and will execute after task1!']
[2025-04-01T00:00:01.727+0000] {subprocess.py:99} INFO - Output:
[2025-04-01T00:00:01.729+0000] {subprocess.py:106} INFO - hey, I am task2 and will execute after task1!
[2025-04-01T00:00:01.729+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-04-01T00:00:01.751+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-01T00:00:01.752+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, run_id=scheduled__2025-03-31T00:00:00+00:00, execution_date=20250331T000000, start_date=20250401T000001, end_date=20250401T000001
[2025-04-01T00:00:01.799+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-01T00:00:01.809+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
