[2025-03-31T08:34:04.834+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-31T08:34:04.854+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v4.first_task manual__2025-03-31T08:34:04.219939+00:00 [queued]>
[2025-03-31T08:34:04.865+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v4.first_task manual__2025-03-31T08:34:04.219939+00:00 [queued]>
[2025-03-31T08:34:04.866+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-31T08:34:04.879+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): first_task> on 2025-03-31 08:34:04.219939+00:00
[2025-03-31T08:34:04.886+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2598) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-31T08:34:04.888+0000] {standard_task_runner.py:72} INFO - Started process 2599 to run task
[2025-03-31T08:34:04.887+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v4', 'first_task', 'manual__2025-03-31T08:34:04.219939+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpf_7pl25c']
[2025-03-31T08:34:04.889+0000] {standard_task_runner.py:105} INFO - Job 86: Subtask first_task
[2025-03-31T08:34:04.934+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v4.first_task manual__2025-03-31T08:34:04.219939+00:00 [running]> on host 9663692256f6
[2025-03-31T08:34:05.023+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='our_first_dag_v4' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-31T08:34:04.219939+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-31T08:34:04.219939+00:00'
[2025-03-31T08:34:05.023+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-31T08:34:05.042+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-31T08:34:05.043+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world, this is the first task!']
[2025-03-31T08:34:05.051+0000] {subprocess.py:99} INFO - Output:
[2025-03-31T08:34:05.053+0000] {subprocess.py:106} INFO - hello world, this is the first task!
[2025-03-31T08:34:05.054+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-31T08:34:05.077+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-31T08:34:05.078+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v4, task_id=first_task, run_id=manual__2025-03-31T08:34:04.219939+00:00, execution_date=20250331T083404, start_date=20250331T083404, end_date=20250331T083405
[2025-03-31T08:34:05.114+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-31T08:34:05.140+0000] {taskinstance.py:3901} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-03-31T08:34:05.142+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
